### PR TITLE
Update BigQuery dataset for option to never expire

### PR DESCRIPTION
**Pull request by Murcurio**
Added option to set default_table_expiration_ms to 0, which will set it to never expire.

### CODE REVIEW

**Comment by ocervell** [comment]
This will prevent creating the dataset when `var.default_table_expiration_ms` is set to another value than "0".

**Comment by Murcurio** [comment]
I haven't tested this specifically, but I just checked my count condition and it seemed to work. The google_bigquery_dataset.dataset resource checks if the var != 0 (anything other than zero) and the google_bigquery_dataset.dataset-noexp resource checks if the var == 0. I did notice I had named both resources as dataset which wouldn't have worked, so updated that.

**Comment by preston-hf** [comment]
This would be a nice feature

**Comment by morgante** [comment]
I'm closing this due to lack of activity.

**Pull request closed without merging**
