### PR TITLE
[WIP] Support for multiple log exports

### PR DESCRIPTION
**Pull request by ocervell**
This adds the following capabilities to this module:
* Ability to specify multiple log exports, filters and destinations (of the same type)
* Current use requires two inter-dependant module calls: merged them for ease-of-use
* More options for Storage buckets, Pub/Sub topics and BigQuery datasets

**WIP:**
- [x] Modules
- [x] Examples
- [x] Tests

### CODE REVIEW

**Comment by aaron-lane** [comment]
@ocervell please request reviews when this is ready.

**Comment by aaron-lane** [comment]
@ocervell besides the significant rebase required, is this ready for review?

**Comment by ocervell** [comment]
On top of a big rebase, I think this rework makes it a bit too confusing to use this module, especially with the multiple list inputs. This was done in the context of merging Fabric work into this module, but Ludo and I agreed to drop this when migrating the Fabric stuff over.

**Comment by morgante** [comment]
Agreed, I'm in favor of closing unless a compelling non-Fabric use case comes up.

**Pull request closed without merging**
