### PR TITLE
fix: upgraded versions.tf to include minor bumps from tpg v5

### PR DESCRIPTION
**Pull request by g-awmalik**

### CODE REVIEW

**Comment by imrannayer** [comment]
Integration is failing with

```
Error: googleapi: Error 429: Existing sinks count: 200 is greater than the limit: 200.
```

**Comment by imrannayer** [comment]
@g-awmalik can u plz clear existing sinks?

**Comment by g-awmalik** [comment]
@imrannayer - this is good to go now.

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
