### PR TITLE
feat: enabling the storage submodule to allow public access prevention

### PR DESCRIPTION
**Pull request by Saloni-Patidar**
fix for issue #169 
"The storage submodule should allow public access prevention #169"

### CODE REVIEW

**Comment by Saloni-Patidar** [comment]
@imrannayer cloud build is failing with error :
 Error: googleapi: Error 429: Existing sinks count: 200 is greater than the limit: 200.

Can you help fix this?

**Comment by Saloni-Patidar** [comment]
@imrannayer Can you please approve this merge request if we are good to go? If not, please let me know.

**Review by imrannayer — DISMISSED** [review]
LGTM

**Comment by imrannayer** [comment]
@Saloni-Patidar Can you plz change min provider version to `4.42` in [version.tf file](https://github.com/terraform-google-modules/terraform-google-log-export/blob/6517b99620b59669592ba01aaf918e46592465af/modules/storage/versions.tf#L23). Feature was GA in provider [4.42](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4420-october-31-2022).

**Comment by Saloni-Patidar** [comment]
@imrannayer updated the version.

**Comment by Saloni-Patidar** [comment]
@imrannayer @g-awmalik the pipeline is failing, can you help with that?

**Comment by g-awmalik** [comment]
> @imrannayer @g-awmalik the pipeline is failing, can you help with that?

This seems like a TGP version issue. Investigating....

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
